# Generated by Django 5.2 on 2025-04-21 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='processo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('estado', models.CharField(blank=True, default='Analizando', max_length=11, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
