# Generated by Django 5.2 on 2025-04-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_processo_latitude_processo_longitude_imagemprotocolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
