# Generated by Django 5.2 on 2025-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_rename_cpf_processo_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
