# Generated by Django 5.2 on 2025-04-24 17:31

import processo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_processo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='cor',
            field=models.CharField(blank=True, default='rgb(248, 51, 84)', null=True),
        ),
        migrations.AlterField(
            model_name='imagemprotocolo',
            name='imagem',
            field=models.ImageField(upload_to=processo.models.rename_protoloco_image),
        ),
    ]
